FROM node:18.17.1-alpine AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . ./

# Construye la aplicación para producción
RUN npm run build

# Etapa de producción
FROM nginx:latest

# Copia los archivos de la etapa de construcción al directorio de Nginx
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto 80
EXPOSE 80
